### ISSUE TITLE
Error when import "react-cas-client"

### ISSUE THREAD

**Issue by MeLoBeats** [alancting/react-cas-client#16]
Hi,

When i want to import the library, i automatically catch this error : 

sax.js:222 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at node_modules/sax/lib/sax.js (sax.js:1565:1)
    at __require (chunk-OL3AADLO.js?v=42ae18b2:9:50)
    at Object.<anonymous> (parser.js:9:9)
    at node_modules/xml2js/lib/parser.js (parser.js:381:4)
    at __require (chunk-OL3AADLO.js?v=42ae18b2:9:50)
    at Object.<anonymous> (xml2js.js:12:12)
    at node_modules/xml2js/lib/xml2js.js (xml2js.js:39:4)
    at __require (chunk-OL3AADLO.js?v=42ae18b2:9:50)
    at index.js:3:16

I'm on react 18.2.0 and ViteJS

![image](https://user-images.githubusercontent.com/109726979/219664059-f618f2f2-bb79-4bd0-b2fa-03d3dba24135.png)

Thanks,
MeLo

**Comment by MeLoBeats** [comment]
![image](https://user-images.githubusercontent.com/109726979/219664248-a67b98c3-8665-4ef6-9fbb-5e53cd0c2366.png)
